apiVersion: v1
kind: Pod
metadata:
  name: mydb
  namespace: sqldb
spec:
  containers:
  - name: mydb
    image: 437005051152.dkr.ecr.us-east-1.amazonaws.com/mydb:v1.3
    env:
      - name: MYSQL_ROOT_PASSWORD
        valueFrom:
          secretKeyRef:
            name: db-creds
            key: password
    ports:
    - containerPort: 3306
  dnsPolicy: ClusterFirst
  restartPolicy: Always