apiVersion: v1
kind: Service
metadata:
  name: mydbservice
  namespace: sqldb
  labels:
    app: mysql
    version: v1
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306